services:
  - type: web
    name: smart-attendance-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: iris-db
      mountPath: /data
      sizeGB: 1
